--- #YAML:1.0
name: Bot-BasicBot-Pluggable-Module-Fun
version: 0.8
author: Simon Wistow <simon@thegestalt.org>
abstract: |-
  various quirky but ultimately useless plugins for Bot::BasicBot::Pluggable
license: perl
requires:
  Acme::Magic8Ball: 1.1
  Bot::BasicBot::Pluggable: 0.1
  Games::Dice: 0
  Lingua::Translate: 0
  Math::Trig: 0
  Test::More: 0
provides: {}
generated_by: Module::Build version 0.25
